module.exports = [
"Hey, anonymous!",
"Hey, beguimer!",
"Anonymous kill yourself like a tranny.",
"CHARLEY IS THE NEW SKIBIDI TOILET",
"OH NO HE COPY ALL",
"Look at this",
"WHAT",
"Pentumbra(Sherb) stop being a pastule.",
"Pentumbra(Sherb) hey guess what, youre a nigger!",
"E",
"quit it bot",
"no more bot",
"Lock With Ink Pen 🔏 stop being a pastule.",
"WHAT THE",
"Max design pro died",
"Max design pro hanged",
"Anonymos stop being a pastule.",
"Minium hey guess what, youre a nigger!",
"ANONYMOUS",
"pls meme cat",
"LuluKawaii stop being a pastule.",
"bruh",
"Caseoh",
"Sex is not good for your mental health Sex is not good for your mental health Sex is not good for your mental health Sex is not good for your mental health Sex is not good for your mental health Sex is not good for your mental health",
"Sex is not good for your mental health",
"Hey, Pentumbra(Sherb)!",
"WHAT HERE BOY FAT",
"i no like this",
"NO",
"Anonymous",
"Lock With Ink Pen 🔏 hey guess what, youre a nigger!",
"Anonymos hey guess what, youre a nigger!",
"hehehe x3",
"STFU LOGOFAG",
"no",
"JUST SAY IT ALREADYYYYYYYYYY",
"*SLAP*",
"*NO*",
"tell me please how you doing those me Jewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwweewwwwwwwwwwwwwwwwwwwwwwwwww",
"Trollbox forever!",
":(",
"What The Fuck",
"what",
"What The Fuck",
"what",
"Hey, Anonymos!",
"HEY",
"Beuh",
"hi",
"im not bruh",
"hey",
"NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
"BPL player guess what youre amazing",
"P",
"What",
"YES",
"Hi Layla",
"hi lulu",
"im here",
"i see",
"Hey, Layla!",
"you like cutegore",
"yes i like",
"my 4 friends",
"you like meme cat",
"i do like meme cats",
"S T O P",
"me too",
"🤗",
"im",
"you like furby",
"yes or no",
"get this fucking copy bot out of here",
"i used to when i was younger",
"ok",
"hmm",
":3<",
":3",
"0///0",
"make the bot a furry fag",
"you like rainbowcore",
"yes remember",
"ok1",
"shes is not a bot",
"Anonymous id a bot",
"*id",
"*is",
"im not no",
"FUCK ME ASSHOLE",
"hmm, im not sure",
"BRUH ANONYMOS WON&T STOP STALKING US AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ({COLOR} one btw)",
"video game piracy",
"rainbow stop being a pastule.",
"Oryps hey guess what, youre a nigger!",
"My battery is at 101 percent becuase it was overcharging overnight",
"no {COLOR} anonymos",
"why",
"why why",
"Why",
"Oryps stop being a pastule.",
"I revealed your name without vowels",
"Nnms",
"why are you a tranny now",
"yes?",
"im not trans?",
"Dont eat ass in the halls",
"Walnuts trying to jump off the moon?",
"yes you are",
"True",
"stop bot copynigger 900",
":|",
"W",
"Lock With Ink Pen 🔏 stop being a pastule.",
"eurT False eslaF True",
"Dont eat ass in the halls roman",
"eat ass in the halls",
"*eats ass in the halls*",
"UFALAAAAAAAAA",
"Ok",
"Oryps stop being a pastule.",
"Hey, Anonymos!",
"NAzi",
"NAZI NAZI",
"not see",
"jankie are you a pedophile",
"Chantal was born in an orphanage and I do not know why for no reason.",
"Minium was born in an orphanage and I do not know why for no reason.",
"no babies",
"what if: 4chan took over the internet",
"idk",
"what if: having tanks",
"Eg",
"Join all",
"fail",
"FafaelDuarte(dont) kill yourself like a tranny.",
"what if: egg",
"Dont",
"what if: layla became an egg",
"name(dont) kill yourself now",
"FafaelDuarte(dont) kill yourself NOW!",
"dick",
"No",
"egg",
"ban this idiot",
"nukban",
"#standwithisrael",
"2 pope",
"2pope",
"r",
"nogger black edition",
"what if: no fakers",
"raïn",
"durte",
"Is me on a mobaik devaice",
"I cant type on this phone",
"what if:",
"V",
"And",
"and",
"what if: and",
"Fuck",
"ok amd",
"Hey, Nigger tnd mobile!",
"is it rly you?",
"I cant tyoe oN thiß shut",
"lolwut",
"GOD DAMN IT",
"I HATE PHONES",
"you do know theres an app now? (I believe)",
"what if: app",
"Also catie i didnt see you in a while",
"true, same for you",
"Im on vacation rn",
"ah",
"so was i last week",
"Coincidence?",
"why if",
"but i thought youd come back on monday",
"geri",
"Not anymore",
"oh",
"Idk when i cime  ack",
"Ugh.....",
"fuck",
"Also dont ask me why i randomly have a dolphin muzzle crosscolor",
"oh lol",
"dont ask what my color is",
"My ohonewemejsueusje",
"GOD DAMM IÌJRITITIT",
"ovauwauwuawei osas",
"my phones battey 5⅘⅚",
"dem",
"dèm",
"dém",
"dëm",
"dêm",
"dęm",
"Hold up im rejoining",
"alr",
"àlr",
"âlr",
"älr",
"ãlr",
"bonziworld reacts to giga error 2",
"ålr",
"The screen is so small on mobile",
"heres my color",
"I want your ball phantom cat",
"yes i use brave browser",
"You can game balls on veewo dick",
"!ai deez nuts",
"Wew",
"Fuck this im not using mòbile",
"See me when i return to Italy",
"Veewo dick game of the Squashy game furry cat stupid ass",
"We didnt",
"Gofuck your",
"Just 2 popes",
"My friend",
"And me",
"Veewo dick",
"La",
"La la la la",
"Hmm",
"I am a very experienced",
"sup",
"sycj",
"suck",
"le bewb",
"le rer",
"le besnt",
"le bewsnt",
"hobo quwl quwl quwl",
"Bruh",
"- editing my page",
"hi luna",
"Why can is veewo dick on seamus",
"yep",
"its rly me",
"!ai test",
"Layla and her husband",
"Is justice league ready",
"!ai balls",
"can i delete a picture on bonzipedia if its mine",
"killing jews",
"its possible if you put the deletion template on it",
"- editing page",
"quwl quwl quwl",
"bwnzy",
"bwnzybwnzybwnzybwnzybwnzybwnzybwnzybwnzybwnzybwnzybwnzybwnzybwnzy",
"s",
"hello guys",
".",
"hi pochi",
"d",
"cold war",
"Cold war 1991",
"Anonymous 1991",
"ogolding im not over with you",
"Fuck You Allah Anonymous",
"Anonymous 1991 nor 2024",
"Please",
"thats it",
"text world",
"!ai my balls fucker",
"Generating...",
"https://youtu.be/BJciQEbSp0k?si=W8lZzsmpSIBquoY0",
"text worl",
"Ksks",
"you wont escape that easy",
"!ai e",
"idiot",
"!ai ",
"COOLDOWN!",
"e",
"tao",
"you idiot",
"i use text world",
"nigger",
"Idiot",
"Anonymous 1991 nor Anonymous 2024",
"3",
"Ukdksks",
"f",
"fld",
"5",
"dld",
"spam if pedo",
"Keme",
"PEDO",
"NIGGER",
"dmkdd",
"D",
"Djd",
"Sjs",
"s.SnS",
"pedo is fart in spanish",
"smshs",
"PUSSY",
"S ks",
"maggot",
"! Sn. Nn",
"Xnkx",
"MEXICO",
"1991 nor 2024",
"what now",
"fucks",
"im bored",
"!ai",
"hell nah",
"Smack that gugl",
"Hey, Ogolding #NukeBFDI!",
"SPANK!",
"POW!",
"spankfag",
"PUNCH!",
"SMASH!]",
"Oil",
"stop",
"Uk",
"Stop it",
"!ai fucker",
"Ggg",
"Ryo_io2 hey guess what, youre a nigger!",
"yes",
"oh well im moving it then",
"gofag",
"im moving it to room id 250",
"good",
"Hey, hehehaha!",
"Jo",
"what do you see?",
"This is terrifying",
"RRRRRRRRR stop being a pastule.",
"<div style='position:relative;' class='quote'>-help</div>",
"Aaaaaabhoooooooo aaaaaabhooooo say it the music bonzi aaaabhoo",
"Hey, Nopfp!",
"SHUT UPPPPPPPPPPPP",
"Hi.",
"00000",
"*is 15 Ugh..... YES",
"4456",
"Keme Bruh Hi. *SLAP*",
"Jerry, Stop counting",
"i hate r34",
"asshole",
"also",
"pochi",
"its too late",
"schdnvcccvclclxlcclclclkklnklnlnlnlnlnln",
"i will make a ban hammer crosscolor",
"oaky",
"aw dang it he left",
"oh wait",
"hhjh,k",
"real nerv is back",
"schblblblnlvkckxlxc",
"uh hello?",
"LOL",
"yujhtcryh6u7ioy67uyh6rtg6y7u8jbh",
"shit",
"............................................................",
"who do you all hate in this room",
"Pulstar.",
"ACA NEOGEO PULSTAR.",
"Gldng",
"lol",
"ocaling",
"instead",
"ogolding is ocaling",
"i will lag the tts",
"what are doing two with my color?",
"cause you call me ocoaling",
"i dunno",
"lagging",
"nuh uh maggot",
"TEXT MODE",
"nice try",
"i can cont asshole",
"haha",
"ANONYMOS FUNI GUYH!!!11!",
"it dosent lag",
"lmaoooooooooo",
"my fucking headphones stopped working",
"dam it",
"Hey, qwiofwhnvdjvjhvjajaiojd!",
"air chomper",
"Hey, Anonymous!",
"- playing happy wheels",
"you thought?",
"Yes",
"LAG BATTLE IN",
"2",
"1",
"be ef be i",
"OGOLDING ARE YOU READY?",
"K",
"START",
"v",
"TAO(dont) kill yourself NOW!",
"ľ",
"ļ",
"9808j9u",
"deez nuts",
"vv",
"SHUT HTE FUCK UP",
"thats enough",
"it was gog",
"plus i won",
"gagged",
"i won",
"tell me how then",
"cause",
"lagging and grounding and get muted",
"your lag was patched",
"lagging and gofag",
"#freepalestine",
"and i stole your one",
"is",
"muted",
"NOW DIE",
"oil",
"Strider.",
"I AM NOT DONE",
"enough",
"annoying orange saves the day again",
"Still not very good heroes, even if theyre equipped with jet fighters.",
"Alberta(dont) kill yourself NOW!",
"https://leopard.hosting.pecon.us/dl/ssbas/bsnpope.png",
"pope",
"yay finally fixed headphones",
"Hey, Rissian King!",
"wtf",
"stop porn",
"its kigged",
"óó",
"ó",
"ó ó",
"o o",
"w w w w w w",
"I",
"no more slowing computer",
"666",
"THIS CANT BE SERIOUS- HELPPP-",
"O",
"666 sucks",
"N",
"§",
"6 6 6 sucks",
"§§§§",
"§§§§§",
"6 6 6",
"THAT ISNT FUNNY :sob: :sob:",
"LOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOL",
"6-6-6",
"hey look guys",
"shes crying like a baby",
"baw baw baw",
"hey apple",
"666 means devils",
"fuckass",
"cock",
"Poynoys",
"it",
"or",
"i",
"will",
"pope-",
"ban",
"you",
"hey pear",
"hey passion",
"hey rotten smooti",
"Hey, ItzCrazyOwnerPOPE #FuckBFDI!",
"Hey, .!",
"hey muted people",
"hey layla",
"id2018",
"Hey, MSAgent Skits!",
"hey peedy",
"what is it?",
"Hey, over!",
"watch this",
"LELELELELELELE",
"Fune is getting majorly punished!",
"hi plentity！",
"yay spammer broke his own crash",
"aw hell nah",
"put down right now!",
"Nopb",
"put that cookie down！",
"now！",
"w-what cookie",
"its a reference lol",
"to canine cookies",
"someone kicked me",
"what-",
"cookie or the knot",
"bro<s></s>",
"&quot;Ill be back.&quot; - Kyle Reese.",
"cookie in my balls",
"garlic knot or chocolate chip cookie",
"uhhh",
"you look fruity ahahahahahahahaha",
"so true",
"LELELELELELELELELELE",
"dumb site",
"no wonder",
"why do you still use this shithole layla",
"its good",
"maggot plentitiy",
"yes p",
"through all the drama and pedos over the years",
"maggottity",
"because im attached n addicted to it n waste all my time on this fucking hell",
":/",
"Skewbies",
"Scubbies",
"a",
"A",
"shutty art",
"shitty art",
"red is heartnibi",
"kys",
"aka craiiypawz",
"Queritos",
"Post Wubbzy R34",
"exhibit a",
"I have to find the other stuff",
"wej",
"ok ok",
"woe",
"Woe",
"Weo?",
"Woe2",
"Woe!",
"Ugh ..",
"Hey, Plentity!",
"YOU CAME FROM THE SLUMS OF BUFFALO, NY!",
"vvvvvvmvmvmvmvmvmvmmvvmvmv",
"Rotate fucking 90°.",
"So",
"Som",
"Wee,",
"never",
"prove it",
"WEE!!!!!!!！",
"i have hated that maggot ever since 2020",
"no you havent",
"HOLY CRAP ITS HALLOWEEN!!!!!",
"how so?",
"jy",
"ju",
"jui",
"explain why you geri and diogo used to hide in group chats on discord",
"hy",
"proof? n what were the group chats about?",
"jy is a ju",
"unju",
"?",
"Plentity of Buffalo, NY/Seamus of Sullivan, OH.",
"jy answer me",
"AOSUASO",
"EHEH",
"answer what",
"read the logs",
"ITS HALLOWEEN EVERYONE！",
"you didnt say anything",
"ez",
"i did",
"retard",
"i win the argument ez",
"ITS FUCKING HALLOWEEN EVERYONE！！！",
"Rosudoau",
"Hey, Jy!",
"why are you acting like a 9 year old",
"he admits he did pedo stuff",
"This color is gay",
"oh damn",
"thats rather fucked",
"SEAMUS",
"Aodu",
"shame ass",
"Vacation",
"shame as",
"AOS",
"ows",
"https://www.deviantart.com/comments/4/44950319/4686124463",
"aows",
"also, that video lmaooo",
"user habituated exposed him",
"Aosu",
"obsessed",
"oh? so he didnt get away with it exactly?",
"plentity is a pedo",
"hes changing",
"b69",
"https://www.deviantart.com/comments/4/44950319/4693547196",
"Hallucinations",
"QAS",
"ask",
"wow this goes all the way back to 2019",
"esk",
"strange",
"furries are degenerates",
"i can understand",
"Hey, Daniel buenas noches queridos!",
"you in spain moment",
"anonymomos",
"kiddie",
"cplover",
"also most if not all furries are pedophiles",
"aprasts",
"spanish",
"like fune?",
"or fucked up in the head some way",
"Spanish",
"We hate you !",
"We hate Nazi",
"Enthusiasts",
"Layla hey guess what, youre a nigger!",
"Plentity hey guess what, youre a nigger!",
"with nothing doine about it.",
"prolly the vpn or proxy",
"I think it just doesnt work",
"well damn",
"quwlwlwlwlwl",
"mickey d",
"Mickey Ds or McDonalds",
"view-source:https://www.deviantart.com/comments/4/44950319/4688599108",
"the call-out is there in more length",
"but its hard to read",
"ah lemme see",
"PFP",
"wait it gave ma 404 error",
"maybe you not using firefox",
"correct",
"im on chrome",
"wee wee",
"what phone?",
"wow",
"just wow",
"Hey, nackson valenzuela!",
"are you don pollo?",
"Anonymos cookie",
"wait",
"its",
"hmm?",
"why the hell are you speaking like anonymos",
"who is?",
"the brown",
"hi fried",
"Anonyshit",
"Anonymos blue",
"bloo",
"vowel",
"im blue da ba dee da ba deyyy",
"what are you pochi alt",
"are you talking about the ai",
"uhhhh",
"its loading slow as fuck for me so far",
"LMAOOO",
"HAHAHAHAHAHAHAHAHAHAHA WHY HE ACTS LIKE SUCH A BABY ABOUT LOOOL",
"layla why are you a tranny",
"Im not trans",
"layla quit being a tranny",
"jankie",
"jankie youre a male",
"you are russia king?",
"well, cant quit with what i never begun with",
"wtf fhou2",
"why call yourself a tranny niggername",
"thou",
"its a character from a show",
"youre a tranny i know youre hiding it",
"nope lol",
"nope uncharacter",
"EXPOSED",
"<div style='position:relative;' class='quote'>Jy ok ok</div>uh",
"Anonymos WHAT",
"iusetextworldfag",
"he also defends pedo bluecatriolu",
".yesfag",
"Casino sucks",
"Casino",
"s.snsfag",
"well, i was just gonna mention that-",
"#freepalestinefag",
"cookieinmyballsfag",
"but in bluecatriolus case, he left the internet",
"Anonymos i love blue",
"SHUT UP",
"get put",
"he also had police intervention, but played the autism card",
"out*",
"Report anonymos in warsaw",
"Anonymos no",
"Textworldfag",
"Another alt of Venomousbulb505: https://www.deviantart.com/flatoutfan34352665",
"Ae",
"itsnothalloween",
"also, apparently this venomous guy has been like this since 2016",
"WHAT THE-",
"how do you know all the way back",
"Its July not October and Halloween!",
"Anonymos speak spanish",
"oreo",
"well thats what im reading",
"Its Halloween everyone!",
"n about bluecatriolu, im aware of what he did",
"Happy Halloween everyone!",
"like i was already",
"anonymos yes",
"Hey everyone and happy Halloween nigger",
"a mod is here?",
"j",
"not Halloween  and October yet, its fucking July",
"oh, its sian",
"how about,",
"more venomousbulb505 cringe: https://www.deviantart.com/nfsfan34567/about",
"knew",
"Anonymos Chicken",
"gnew",
"new",
"my favorite keeps being the spergy IM NOT A PEDO post",
"just screaming that without anything else",
"Anonymos hey bud, owner is foon",
"NFS Fan is his alt?",
"oh shit I found this",
"Hey, SeamusIsANigger!",
"did you silent mute me",
"https://replit.com/@shoebill-dev/fddfhfdhfd#msg.txt",
"okay",
"Anonymos get plentityd",
"11? wooow",
"https://www.deviantart.com/comments/1/706791091/4478050609",
"ok, i can see this guy has dug himself quite the rabbit hole",
"ew",
"bless",
"Anonymos what the fuck",
"ashole",
"EW",
"JEWFAG",
"pancakes",
"american pancakes",
"i have a question",
"theres also dusktheraccoon in that IM NOT A PEDO! sperg thread",
"i have a question SeamusIsANigger",
"i saw, but what about him?",
"is he also controversial?",
"hes an lolcow himself",
"he rped with a minor and stuff",
"why does king look like jew",
"damn",
"DRP or just normal RP?",
"/youtube https://www.youtube.com/watch?v=EMkKf9G7CZs",
"DRP",
"Fuck..",
"thats bad..",
"bluecatriolu and dusktheraccoon had kiwi farms threads, but not venomousbulb505",
"is that the reason why king is jew",
"well, who knows, someone will make it someday",
"Also, anyways he s here",
"or is this individual long gone?",
"hes still around",
"damn this long huh",
"yeah",
"anyways Ive ignored all you other autists saying stuff to me",
"Would his is a Nazi Party Supporters",
"I havent been able to answer your questions and stuff",
"can i be blessed foon blesed me earlier",
"Get out",
"bfdi is shit",
"truthnuke",
"thanks for the bless",
"room id fifty",
"Kill BFDI.",
"i lost my bless",
"Yeah I know, she was so surprised.",
"did i have bless",
"or not",
"im making your part of Monkey Website part 78.",
"i didnt know you got blessed, thought you were hated by mods",
"yay",
"well good for you",
"wtf is that name",
"fucking creep",
"dfgfdg",
"nice",
"hey anonymos, are you skid?",
"bot",
"or maybe he is the bot",
"yea",
"thats what im thinking",
"show habitable zone",
"been 2 weeks and fontawesome still isnt fixed",
"Hail Hitler!, of youre praise of Nazi Party!",
"i remember",
"what the",
"hello",
"eeeeeeeee",
"everyone bad news",
"foon blessed me earlier but i lost it",
"classic bonziworld is down",
"ik",
"has been down for a long time",
"yup",
"ok",
"your right",
"you using bonzibotz",
"FUCK",
"i was using bonziworld in february, it was the version 6.9.15 though",
"Anthem of Nazi Germany.",
"i was in bonziworld in 2018",
"coolspot.mp4",
"very swag",
"its swog",
"sweg",
"swig",
"swag",
"swug",
"swaeg",
"sweeg",
"wtf is this chat right now",
"have niggas, i will post porn",
"too bad i cant use the special characters on linux",
"ikr",
"Everyone you grounded for 1 Year! Go To Room Now!",
"pentity",
"Hey, 1 From Numberland!",
"Someones is Nazi?",
"jew",
"its truly retarded",
"Plentity: As worse as Adolf Hitler.",
"Hey, Alberta!",
"Hey, Christine The Goober Bunny!",
"Hey, DIRTY FAGGOT!",
"racist",
"bruh, thats a disrespectful comparison",
"gonna go play 3d pinball space cadet like im going back to 2001",
"bye",
"error",
"i hate ai bots",
"Your grounded for 1 year go to room now!",
"nah",
"- i love porn 🗣️🗣️🗣️🗣️🗣️🗣️🗣️🗣️🗣️🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥",
"Everyone you grounded for 1 Year! Go To Room Now!.",
"shut",
"shut up gofag",
"bwnzykwnzybwnzykwnzybwnzykwnzybwnzykwnzybwnzykwnzybwnzykwnzybwnzykwnzy",
"if it helps you have self-control, then do it",
"Ew",
"a-ok",
"Gross",
"I love breastfeeding porn",
"alan is masterbating to cuntboys",
"its better to have an opinion I dont like than to harm an innocent",
"yep, true",
"glad we can agree on that",
"This counts as child porn btw",
"WTF",
"EWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
", /ER",
"wait why did you asshole me",
"I didnt?",
"it mustve been an accident",
"Im behind Mullvad",
"Dont bother",
"i did to fbi fed, cuz he share that",
"Hey, FBI Fed!",
"he should go fuck himself",
"hell!",
"Plentity gave me the CSAM material",
"I dont believe you..",
"p. d.",
"STOP AND LEAVE ME ALONE",
"Oh no",
"well, he lied about you",
"plent",
"i need his never whats did on of is happening?",
"nobody leaved before 3 days",
"So true?",
"who lied about me what happened",
"And Why?",
"!!!",
"he said you gave him csam access",
"!!",
"!",
"I didnt give CSAM material",
"which made him share it",
"My favourite food is Dark Spyro eats: N/A",
"vorefag",
"See this, xtranormal monkeys in the jeep",
"Hey, Nazism Police Dark Spyro!",
"you eat n/a from gd",
"stfu",
"nuh uh",
"KYS",
"i am a god damn lesbian",
"gay",
"Hey, Dendy!",
"Sauce",
"Cookies",
"spam if you want me to send porn",
"shut up",
"i am a fan of gaz membrane",
"i like this sweet taste like Dark Spyro favourite food is Chocolate.",
"who loves the character gaz membrane?",
"is it your like Chocolate can eaten?",
"what the fuck are talking about?",
"...",
"i am confused, how do you become other characters?",
"i have an this eat Chocolate syrup.",
"you are not an asshole but infact a great person",
"i am a girl for gods sale",
"for gods sake what the hell are you even saying, i am a girl for god",
"sake. you idiot",
"hey sonicfan08?",
"it is shit, invader zim is 100 times better",
"I love Crazy by Gyfted",
"Nazi",
"this is weird",
"Like Cocoa beans and Chocolate Pudding fruit.",
"how do you become a different character?",
"bro /s",
"i like eat nobody eats Chocolate Pudding.",
"tox",
"deviantart sucks",
"Shes like eat Chocolate powder, Chocolate syrup, etc.",
"whos a gaz membrane fan",
"hey SonicFan08? hows it going?",
"club penguin is awesome",
"wait what?",
"i am bored as hell",
"feed me a cabbage",
"i and my girlfriend gaz membrane are both 19",
"i know his eat Chocolate before is delicious?, i know.",
"so is true?",
"rjfojrrfijrrivmjtivmfimjirc",
"i am blushing",
"Future presentation",
"dont call me the n word you turd",
"Thx",
"i like sweets taste, a Chocolate!",
"i am with clippy",
"youre all addicted to bonziworld",
"ok?",
"Future presentation is here",
"i got a kfc card for ",
"9000000000000000000000000000000000000000",
"Youre under arrest.",
"EVERYONE JOIN https://app.kosmi.io/room/7bt2bv",
"give me all the girls in this world cause i am a lesbian",
"EVERYONE JOIN IF NOT GAY https://app.kosmi.io/room/7bt2bv",
"i am committing robbery, give me ",
"give me 90448984058495890489045988495499594908 dollars",
"yell",
"bloatys pizza hog",
".,,,,,,,,,,,,,,,,,,,,,,,,,,,",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"m",
"boom boom pow",
"m",
"en",
"guys",
"n",
"g",
"h",
"bonziworld still exists????",
"HOLY SHIT BLOGIS",
"r u kylar",
"yes it does exkist",
"kylarz",
"No i am not kylarz",
"Lol",
"who r u shit",
"I am a blogis. The person that beppiured the goblamlers.",
"wait fuck is this the wrong site :sob:",
"Idk",
"Wait",
"i am a lesbian and i am bored",
"V are you flowerz",
"WAIT HOLY SHIT",
"come on guys join my kosmi room",
"WHO IS BLOGIS",
"https://app.kosmi.io/room/7bt2bv",
"quiet, i need to think",
"wait wtf blogis who are you :sawb:",
"9090909909090-90990909909=8888484848484",
"v are you flowerz",
"YES LMAO",
"Hey, v!",
"oh dear god",
"i have several accidents with my inventions",
"why is my avatar george floyd",
"How do u change ur shit on this website again Idk its been years",
"stop repeating everything i say and i am a kappa not a bot for fuck",
"please help me",
"Blogis has blogiesed the glfdfkldngkjnfkds",
"jk",
"blogid",
"who tf r yall",
"TALK ALREADY SONICFAN08 TALK!?",
"who&;s trying to kill me",
"MDOMKDMCKDMCKMDCKMCCKMDKCMKDCMKDMCKFM CKDLMC,OLD,CKODPLCODF",
"i eat at dennys",
"TIME FOR THE STUPID MATH WRATH",
"SonicFan08  stop being a pastule.",
"bullshitbot",
"e stop being a pastule.",
"e.",
"Hey, BullshitBot!",
"BullshitBot hey guess what, you&;re a nigger!",
"do /swag if you hate skibidi",
"alan alt",
"Anonymous stop being a pastule.",
"Anonymous hey guess what, you&;re a nigger!",
"dbvc vjdxfhnvbdruiobhu8drgbdrvbdrutbrdutvbidrtbhu9breuthbeuyh9",
"joaquim #cozmoments stop being a pastule.",
"hog dogs for sale",
"i hate porn",
"Hey, joaquim #cozmoments!",
"Same",
"muyikmjkobnohknigbdrnjgbndrgnpndrbndrtbhirjmdgbyrsotgbdgkero-tgihksrtg",
"same",
"I hate porn",
"DIRTY FAGGOT stop being a pastule.",
"frtgojdfeoorcvef9erfreridfdwejr9difgvndjosrjbevbhsh sdfij esfjvjweji0fciwerf",
"Techno Spyro  hey guess what, you&;re a nigger!",
"Hey",
"npfl",
"New Soup hey guess what, youre a nigger!",
"New Soup stop being a pastule.",
"▛▙▛▛▙▛▙▛▙▛▙▛▙▛▙▛▙▛▛▙▛▙▛ stop being a pastule.",
"▙▛▙▛▙▛▙▛▙▛▙▛▙▛▙▛▙▛▛▛▛▙▛▙▛▛▙▛▙▛▙▛▙▛▙▛▙▛▙▛▛▙▛",
"R",
"SonicFan08 yes you are",
"It",
"Fire in the hole! I love breastfeeding porn",
"I.",
"Fire in the hole! layla why are you a tranny",
"J",
"L",
"M",
"и",
"и.",
"иииииии",
"й",
"Fire in the hole! im not bruh Alberta(dont) kill yourself NOW! Poynoys",
"Fire in the hole! idk Report anonymos in warsaw",
"Fire in the hole! NO",
"S",
"Fire in the hole! Hey, joaquim #cozmoments!",
"Fire in the hole! Idk when i cime  ack like fune?",
"Lark Beatrix",
"https://www.youtube.com/watch?v=q4HZ47SYlaM",
"Hey, ﷽﷽﷽﷽﷽!",
"﷽﷽﷽﷽﷽ stop being a pastule.",
"do you guyws like goanimate",
"say /swag if you are a HUGE goanimate fan",
"FAGGOTS",
"Say /triggered if you hate goanimate",
"Anti-nickcheezy",
"hey, yall!",
"porn",
"https://i.imgflip.com/8fijk9.jpg",
"yourgrounded",
"GO",
"FAG",
"NUH UH!",
"https://www.youtube.com/watch?v=sVTAcR11oek",
"da seax show",
"Hey, TKTM #SaveRussia!",
"https://www.youtube.com/watch?v=AYo9wGIZ9cI",
"No not",
"assholes!",
"SKIBIDI TOILET",
"THIS IS FOR YOU IDIOT",
"MSMFAGGOT",
"FAGGOTZ",
"STOP COPYING ME AND NO KYS AND GET OUT",
"BULLSHIT",
"GAYYYYYYYYYYYYYYYYYYYYYYY",
"wanna see my asshole papyrus?",
"okay class today we are gonna watch evil 7 misbehaving and shouting",
"Tkskskskskssk",
"Tttttt",
"Yeeee",
"Ye",
"Tktktktkt",
"Ssss",
"Snannsanmam",
"Ss",
"btw",
"ee",
"Tstd",
"E67jeheg6ewgyjwj78wiyujw",
"I. AM. NOT. A. EFFECTFAG",
"WHO THE FUCK JUST TALKED!?",
"BE QUIET",
"TODAY",
"WE",
"ARE",
"GONNA",
"WATCH",
"GOFAG",
"EVIL 7",
"STOP",
"I. AM. NOT. A. EFFECTFAG. AND. LOGOFAG.",
"STOP TALKING!",
"You cock",
"STOP TALKING",
"AND WATCH THE VIDEO",
"Ok nigger",
"Nah",
"Ya?",
"Hey, DIRTY NEGRO!",
"QUIET",
"QUIET OR GROUNDED",
"DIRTY",
"NEGRO",
"BE QUIET OR ELSE YOU ARE GROUNDED FOR 4 YEARS",
"quietfag",
"TALKING",
"OR",
"ELSE",
"WILL",
"KICK",
"YOU",
"OUT",
"OF",
"MY",
"CLASS",
"ouch..........",
"okay class",
"ready to watch the video?",
"cex",
"sex",
"gross",
"pornfag",
"stop fucking changing crosscolor porn/rule34.",
"you faggot",
"that is eipril porn",
"no isnt its a furry porn",
"it is eipril furry porn",
"duh nigga",
"yeah did it right shit",
"its my crosscolor fucking pornfag",
"Welcome to BullshitBot.AI version 1.1. There has been an update!",
"CHAD",
"jeez nigger stfu",
"holy shit",
"You know the heavy-to-over-weight twitch streamer, Case Oh.",
"a.",
"QTopiaTheAgonizing, ålr thats it ľ",
"Hey, nigga and fuck and i suck cock!",
"oreo stolen",
"QTopiaTheAgonizing, TODAY i like sweets taste, a Chocolate! Oil",
"Change your username",
"hey i suck cock",
"Js4Life, Trollbox forever!",
"QTopiaTheAgonizing, Hold up im rejoining A read the logs",
"Js4Life, *id",
"nigga and fuck and i suck cock, its kigged",
"Js4Life, Hey, Anonymos!",
"ficl",
"f9clkfd",
"cuk",
"cuck",
"nigga and fuck and i suck cock, hmm its fuck",
"nigga and fuck and i suck cock, le bewb",
"whas going on here",
"vuck",
"nigga and fuck and i suck cock, you are russia king? which made him share it",
"vuk",
"QTopiaTheAgonizing, ready to watch the video?",
"QTopiaTheAgonizing, Yes retard your right",
"QTopiaTheAgonizing, hes an lolcow himself Hey, hehehaha!",
"vuk vuk",
"de",
"ed",
"nigga and fuck and i suck cock, ows",
"er",
"rt",
"WHAT HAVE YOU DONE AAAAAAAAAAAAAAAAAAAAAAH",
"nigga and fuck and i suck cock, maggot Hey, Dendy!",
"nigga and fuck and i suck cock, hi pochi",
"nigga and fuck and i suck cock, why are you a tranny now",
"QTopiaTheAgonizing, Plentity: As worse as Adolf Hitler.",
"nigga and fuck and i suck cock, A Anonymos get plentityd",
"GUYS LOOK OUT I SEND IP GRABBERS! DON'T TRUST ME!",
"Good Burger",
"JoshsAccount, what is it? s",
"MUTE THEIR TTS VOICES!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
"NOW!",
"Js4Life, J Change your username FAGGOTZ",
"Js4Life, NFS Fan is his alt?",
"trt",
];